sudo: 'required'

services:
  - 'docker'

before_install:
  - sudo apt-get update \
    && apt-get -y install shellcheck

script:
  - 'make lint'
  - 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      make push-image
    fi
